#!/usr/bin/env bash
# sFlow Analytics — install or upgrade from this package.
#
#   sudo ./install.sh            # install (or upgrade: data and settings are kept)
#   sudo ./install.sh --demo     # also start a synthetic traffic generator (no switch needed)
#
# Options (environment variables, rarely needed):
#   SFLOW_DIR=/opt/sflow-analytics   installation directory
#   HTTPS_PORT=443 HTTP_PORT=80 SFLOW_PORT=6343   host ports (first install only)
#   SFLOW_PROJECT=sflow-analytics     Docker Compose project name
set -euo pipefail

PKG="$(cd "$(dirname "$0")" && pwd)"
VERSION="$(cat "$PKG/VERSION")"
DIR="${SFLOW_DIR:-/opt/sflow-analytics}"
DEMO=0
for a in "$@"; do
  case "$a" in
    --demo) DEMO=1 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown option: $a" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1;33m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m ok\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || exec sudo -E "$0" "$@"
[ "$(uname -m)" = "x86_64" ] || die "this package is for x86_64 (amd64) Linux; this host is $(uname -m)"

echo
echo "  sFlow Analytics $VERSION — installation in $DIR"
echo

# --- Docker ------------------------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  if command -v apt-get >/dev/null 2>&1; then
    say "Installing Docker from the distribution packages (docker.io, docker-compose-v2)"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq docker.io docker-compose-v2 >/dev/null || die "Docker installation failed; install Docker Engine + Compose v2 and run again"
    systemctl enable --now docker >/dev/null 2>&1 || true
  else
    die "Docker is not installed. Install Docker Engine and the Compose plugin, then run again."
  fi
fi
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is missing (package docker-compose-v2 or docker-compose-plugin)"
ok "$(docker --version | cut -d, -f1), $(docker compose version --short 2>/dev/null || echo compose v2)"

# --- first install or upgrade --------------------------------------------------------------
UPGRADE=0
[ -f "$DIR/.env" ] && UPGRADE=1
if [ "$UPGRADE" = 1 ]; then
  say "Existing installation found ($(grep '^APP_VERSION=' "$DIR/.env" | cut -d= -f2)): upgrade to $VERSION, data and settings kept"
else
  free_gb=$(df -BG --output=avail "$(dirname "$DIR")" | tail -1 | tr -dc 0-9)
  [ "${free_gb:-0}" -ge 20 ] || say "warning: only ${free_gb} GB free; plan 50 GB or more (see the sizing table in QUICKSTART.md)"
  for p in "${HTTPS_PORT:-443}/tcp" "${HTTP_PORT:-80}/tcp" "${SFLOW_PORT:-6343}/udp"; do
    n=${p%/*}; proto=${p#*/}
    if ss -lnH "$( [ "$proto" = udp ] && echo -u || echo -t )" "sport = :$n" 2>/dev/null | grep -q .; then
      die "port $p is already used on this host (set HTTPS_PORT / HTTP_PORT / SFLOW_PORT to use other ports)"
    fi
  done
fi

# --- images ------------------------------------------------------------------------------
say "Loading the images (about a minute)"
gunzip -c "$PKG/images.tar.gz" | docker load -q >/dev/null
ok "images loaded"

# --- files and configuration ---------------------------------------------------------------
install -d -m 755 "$DIR" "$DIR/clickhouse"
install -m 644 "$PKG/compose.yml" "$DIR/compose.yml"
install -m 644 "$PKG/clickhouse/sflow.xml" "$DIR/clickhouse/sflow.xml"
install -m 755 "$PKG/uninstall.sh" "$DIR/uninstall.sh"
install -m 755 "$PKG/backup.sh" "$DIR/backup.sh"
install -m 644 "$PKG/QUICKSTART.md" "$DIR/QUICKSTART.md"
[ -f "$PKG/LICENSE" ] && install -m 644 "$PKG/LICENSE" "$DIR/LICENSE"
install -m 644 "$PKG/VERSION" "$DIR/VERSION"

IP="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src") print $(i+1)}' | head -1)"
IP="${IP:-$(hostname -I | awk '{print $1}')}"
if [ "$UPGRADE" = 0 ]; then
  # finite input: no SIGPIPE ("tr: write error: Broken pipe") under pipefail
  rnd() { head -c 1024 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c "1-$1"; }
  TZ_NAME="$(timedatectl show -p Timezone --value 2>/dev/null || echo UTC)"
  umask 077
  cat > "$DIR/.env" <<EOF
# sFlow Analytics configuration — generated by install.sh on $(date -u +%F).
# Change a value, then: cd $DIR && sudo docker compose up -d
APP_NAME="sFlow Analytics"
APP_VERSION=$VERSION
APP_TIMEZONE=${TZ_NAME:-UTC}
SFLOW_PROJECT=${SFLOW_PROJECT:-sflow-analytics}
HTTPS_PORT=${HTTPS_PORT:-443}
HTTP_PORT=${HTTP_PORT:-80}
SFLOW_PORT=${SFLOW_PORT:-6343}
# Days of detailed flows and counters (the hourly history used by Trends is kept 3 years)
RETENTION_DAYS=90
DISK_MAX_USAGE_PERCENT=85
CLICKHOUSE_DATABASE=sflow
CLICKHOUSE_USER=sflow
CLICKHOUSE_PASSWORD=$(rnd 32)
TLS_COMMON_NAME=sflow-analytics
TLS_EXTRA_SAN=IP:$IP
AUTH_ENABLED=true
ADMIN_USERNAME=admin
# Initial password of the web user "admin" (a new one is required at first sign-in)
ADMIN_PASSWORD=sflow
LOG_FORMAT=json
EOF
  ok "configuration written to $DIR/.env (random database password)"
else
  sed -i "s/^APP_VERSION=.*/APP_VERSION=$VERSION/" "$DIR/.env"
fi
chmod 600 "$DIR/.env"

# Larger UDP receive buffers: no sFlow datagram lost during bursts.
cat > /etc/sysctl.d/90-sflow-analytics.conf <<'EOF'
net.core.rmem_max = 33554432
net.core.rmem_default = 8388608
EOF
sysctl -q --system >/dev/null 2>&1 || true

# --- start -------------------------------------------------------------------------------
say "Starting"
cd "$DIR"
PROFILE=()
[ "$DEMO" = 1 ] && PROFILE=(--profile demo)
docker compose "${PROFILE[@]}" up -d --remove-orphans >/dev/null 2>&1 || docker compose "${PROFILE[@]}" up -d --remove-orphans
. "$DIR/.env"
URL="https://$IP$( [ "${HTTPS_PORT:-443}" = 443 ] || echo ":$HTTPS_PORT")/"
WAIT="${SFLOW_WAIT:-300}"   # seconds to wait for the web interface (first start)
for i in $(seq 1 $((WAIT / 2))); do
  if curl -sk -o /dev/null -w '%{http_code}' "https://127.0.0.1:${HTTPS_PORT:-443}/api/v1/health" 2>/dev/null | grep -q 200; then
    break
  fi
  [ "$i" = $((WAIT / 2)) ] && die "the application did not become ready in $((WAIT / 60)) minutes: cd $DIR && sudo docker compose logs"
  sleep 2
done
ok "running"

echo
echo "  ────────────────────────────────────────────────────────────────────"
echo "   sFlow Analytics $VERSION is ready"
echo
echo "   Web interface   $URL"
echo "                   (self-signed certificate: accept the browser warning)"
if [ "$UPGRADE" = 0 ]; then
  echo "   User            admin"
  echo "   Password        sflow   (a new password is required at first sign-in:"
  echo "                            sign in now, before exposing the appliance)"
fi
echo
echo "   Send sFlow to   $IP  UDP ${SFLOW_PORT:-6343}"
echo "   RUCKUS ICX:     sflow destination $IP ${SFLOW_PORT:-6343}"
echo "                   sflow sample 512"
echo "                   sflow polling-interval 20"
echo "                   sflow enable"
echo "                   interface ethernet 1/1/1 to 1/1/48"
echo "                    sflow forwarding"
[ "$DEMO" = 1 ] && echo "   Demo traffic    5 synthetic switches are sending sFlow (stop: cd $DIR && sudo docker compose stop generator)"
echo
echo "   Files           $DIR  (QUICKSTART.md, backup.sh, uninstall.sh)"
echo "  ────────────────────────────────────────────────────────────────────"
echo
